### ISSUE TITLE
Question: ClassNotFoundException: akka.persistence.hazelcast.Journal

### ISSUE THREAD

**Issue by tomer-ben-david** [sorokinigor/akka-persistence-hazelcast#11]
Any reason you can think of or already seen this that i get this exception althought I have it in classpath?

`"com.github.sorokinigor" % "akka-persistence-hazelcast_2.11" % "1.1.0",`

thanks

**Comment by sorokinigor** [comment]
Hey Tomer,
Do you have a stacktrace? Do you use hazelcast in client or cluster mode?

**Comment by tomer-ben-david** [comment]
Hi, sorry I'll close this, I moved on since then, not sure if I found the root cause or not.  thanks.
