### ISSUE TITLE
Allow for file based hazelcast.xml loading as well as class path hazelcast.xml loading

### ISSUE THREAD

**Issue by ekskimn** [sorokinigor/akka-persistence-hazelcast#12]

**Comment by ekskimn** [comment]
We are using the library but we need to be able to pass the hazelcast.xml config by file reference out side of the class path.  But because you're only using 

     new ClasspathXmlConfig(config.getString("config-file"))

we can't reference files outside of the class path.  It would be great to allow use of 

    new FileSystemXmlConfig(config.getString("config-file"))

**Comment by sorokinigor** [comment]
Hi @ekskimn ,
It sounds like an easy change, I will take care of it this week.

**Comment by sorokinigor** [comment]
@ekskimn
I have published 1.1.1 version with the fix ( 'com.github.sorokinigor:akka-persistence-hazelcast_2.11:1.1.1').
It should be available within a day (it depends on Maven Central).

**Comment by ekskimn** [comment]
@sorokinigor awesome~!  thank you~!
